"""Auto-play backend: build a contiguous segment plan for the timeline.

The frontend orchestration serves each segment's mp4 via:

  * Clips with ``playback.mp4`` → dubbed audio + video slice (no burned sub).
    The HTML/CSS overlay renders the Esperanto text live.
  * OP / ED → one contiguous ``_playback/op.mp4`` or ``_playback/ed.mp4``
    (generated by "Generate Previews").
  * Everything else (gaps, un-previewed clips) → a short lived ffmpeg slice
    of ``video_only + original audio``.

This module itself does NOT touch ffmpeg or produce cached files.
"""
import logging
from pathlib import Path

_log = logging.getLogger("anidub.playback")


def _gap_seg(s: float, e: float) -> dict:
    return {
        "kind": "gap", "clip_id": None, "start": s, "end": e,
        "dubbed": False, "status": None,
        "original_text": None, "translated_text": None,
        "ready": False,
    }


def _is_playback_ready(proj, clip_id: str) -> bool:
    pb = proj.path / "lines" / clip_id / "playback.mp4"
    return pb.exists() and pb.stat().st_size > 1024


def _op_ed_ready(proj, name: str) -> bool:
    pb = proj.path / "_playback" / f"{name}.mp4"
    return pb.exists() and pb.stat().st_size > 1024


def get_playback_plan(proj) -> dict:
    """Walk timeline in order, producing contiguous segments covering the
    full episode. OP and ED are collapsed into single segments; overlapping
    clip lines within them are skipped."""
    proj._init_timeline()
    bounds = proj.get_timeline_bounds()
    if not bounds or bounds[1] <= bounds[0]:
        return {"segments": [], "total_start": 0.0, "total_end": 0.0,
                "total_duration": 0.0, "selected_clip_id": proj.state.get("selected_clip_id")}

    total_start, total_end = bounds
    clips = proj.get_timeline_clips()
    op_s, op_e = proj.state.get("op_range", (0.0, 0.0))
    ed_s, ed_e = proj.state.get("ed_range", (0.0, 0.0))
    if op_e <= op_s:
        op_e = 0.0
    if ed_e <= ed_s:
        ed_e = 0.0

    segments: list[dict] = []
    cursor = float(total_start)

    for c in clips:
        s = float(c["start_sec"])
        e = float(c["end_sec"])
        status = c.get("status")

        # If this clip falls entirely inside OP or ED and is non_dub, skip
        if op_e and s >= op_s and e <= op_e and status == "non_dub":
            continue
        if ed_e and s >= ed_s and e <= ed_e and status == "non_dub":
            continue

        if e <= cursor + 0.001:
            continue
        if s <= cursor:
            s = cursor
        elif s > cursor + 0.001:
            segments.append(_gap_seg(cursor, s))

        seg = {
            "kind": "clip",
            "clip_id": c["clip_id"],
            "start": s,
            "end": e,
            "status": status,
            "original_text": c.get("original_text"),
            "translated_text": c.get("translated_text"),
            "character": c.get("character"),
            "dubbed": bool(c.get("clone_path")),
            "ready": _is_playback_ready(proj, c["clip_id"]),
        }
        segments.append(seg)
        cursor = max(cursor, e)

    if cursor + 0.001 < total_end:
        segments.append(_gap_seg(cursor, total_end))

    # Now inject OP / ED single-segment placeholders.
    # The plan must stay sorted by start, so split+merge rather than simple
    # prepend/append.
    if op_e:
        op_seg = {
            "kind": "clip", "clip_id": "__op__",
            "start": op_s, "end": op_e,
            "status": "non_dub", "dubbed": False,
            "original_text": None, "translated_text": None,
            "character": None,
            "ready": _op_ed_ready(proj, "op"),
        }
        # Insert before the first segment that starts at or after op_e
        segments = _inject_placeholder(segments, op_seg)
    if ed_e:
        ed_seg = {
            "kind": "clip", "clip_id": "__ed__",
            "start": ed_s, "end": ed_e,
            "status": "non_dub", "dubbed": False,
            "original_text": None, "translated_text": None,
            "character": None,
            "ready": _op_ed_ready(proj, "ed"),
        }
        segments = _inject_placeholder(segments, ed_seg)

    return {
        "segments": segments,
        "total_start": float(total_start),
        "total_end": float(total_end),
        "total_duration": float(total_end - total_start),
        "selected_clip_id": proj.state.get("selected_clip_id"),
    }


def _inject_placeholder(segments: list[dict], placeholder: dict) -> list[dict]:
    """Insert *placeholder* at its chronological position. Replace any
    gaps or clip segments that it fully covers, and clip any segment it
    partially overlaps."""
    ps = float(placeholder["start"])
    pe = float(placeholder["end"])
    result: list[dict] = []

    for seg in segments:
        ss = float(seg["start"])
        se = float(seg["end"])

        # Segment entirely before placeholder range
        if se <= ps + 0.001:
            result.append(seg)
            continue

        # Segment entirely after placeholder range (stop processing)
        if ss >= pe - 0.001:
            if not placeholder.get("_injected"):
                result.append(placeholder)
                placeholder["_injected"] = True
            result.append(seg)
            continue

        # Overlap — segment starts before placeholder
        if ss < ps - 0.001:
            result.append(_gap_seg(ss, ps))

        # Segment extends past placeholder — keep the tail
        if se > pe + 0.001:
            if not placeholder.get("_injected"):
                result.append(placeholder)
                placeholder["_injected"] = True
            tail = dict(seg)
            tail["start"] = pe
            result.append(tail)
            continue

        # Segment fully inside placeholder → drop it

    if not placeholder.get("_injected"):
        result.append(placeholder)

    # Re-sort by start
    result.sort(key=lambda s: s["start"])
    return result
